name: Install of Ruby 2.0.0 (cached)

on: push

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    # - uses: actions/cache@preview
    #   id: cache
    #   with:
    #     path: ~/local/rubies
    #     key: ruby-2.0
    - uses: ./.github/actions/build
      id: ruby
      with:
        ruby-version: 2.0.0-p648
        cache-available: ${{ steps.cache.outputs.cache-hit == 'true' }}
    - name: Print version
      run: ${{ steps.ruby.outputs.ruby-path }} --version
    - name: Print OpenSSL version
      run: ${{ steps.ruby.outputs.ruby-path }} -ropenssl -e 'puts OpenSSL::OPENSSL_LIBRARY_VERSION'
      
